// DevJay Tools — central tool registry. Single source of truth for the hub.
// Each entry drives card rendering, the tab/category filter, and the search index.
//
// Fields:
//   id              — stable slug
//   title           — display name
//   description     — short one-liner shown on the card
//   longDescription — fuller text used by search
//   category        — one of CATEGORIES below
//   tags            — extra keywords for search (synonyms)
//   url             — where the card links to. Use relative paths while tools live in this repo;
//                     change to full URLs (subdomains) when tools move to independent deployments.
//   status          — 'live' | 'coming-soon'. 'coming-soon' cards are visible but not clickable.
//
// Add a new tool: append to TOOLS below and it'll show up in the right tab + search.

const CATEGORIES = [
  { id: 'all',   label: 'All'       },
  { id: 'image', label: 'Image'     },
  { id: 'audio', label: 'Audio'     },
  { id: 'video', label: 'Video'     },
  { id: 'ai',    label: 'AI'        },
  { id: 'dev',   label: 'Dev Tools' },
  { id: 'text',  label: 'Text'      },
];

const TOOLS = [
  {
    id: 'image-editor',
    title: 'Image Editor',
    description: 'Crop, resize, add shapes and text to your photos — all in your browser.',
    longDescription: 'A simple image editor that works like a lightweight paint program. Add rectangles, circles, lines, and text with custom colors and fonts. Resize and compress before downloading. Your photos never leave your device.',
    category: 'image',
    tags: ['resize', 'crop', 'compress', 'shapes', 'text', 'draw', 'paint', 'jpeg', 'png', 'webp', 'photo', 'annotate'],
    url: './image-editor/',
    status: 'live',
  },
  {
    id: 'folder-tool',
    title: 'Folder Creator',
    description: 'Type out folder names and download the real folder structure as a .zip.',
    longDescription: 'List your folders and files, click a button, get a .zip file with the whole structure ready to unzip anywhere. Also makes clean folder diagrams you can paste into a README.',
    category: 'dev',
    tags: ['folder', 'directory', 'tree', 'ascii', 'readme', 'structure', 'scaffold', 'zip', 'project'],
    url: './folder-tool/',
    status: 'live',
  },
  {
    id: 'prompt-enhancer',
    title: 'Prompt Enhancer',
    description: 'Turn a rough idea into a detailed AI prompt for ChatGPT, Claude, Midjourney, or Stable Diffusion.',
    longDescription: 'Paste a vague prompt, pick the AI tool you use, and get back a polished version that gives better results. Powered by Google Gemini. Free to use.',
    category: 'ai',
    tags: ['prompt', 'chatgpt', 'midjourney', 'claude', 'stable diffusion', 'gemini', 'ai', 'llm', 'generator'],
    url: './prompt-enhancer/',
    status: 'live',
  },

  // Roadmap — flip to 'live' as they're built.
  {
    id: 'youtube-looper',
    title: 'YouTube Replay',
    description: 'Loop a specific part of any YouTube video for practice or review.',
    longDescription: 'Pick a start and end time, play that section on repeat. Useful for language practice, music transcription, dance, or re-watching a specific moment.',
    category: 'video',
    tags: ['youtube', 'loop', 'replay', 'segment', 'repeat', 'practice', 'language'],
    url: './youtube-looper/',
    status: 'live',
  },
  {
    id: 'audio-trimmer',
    title: 'Audio Trimmer',
    description: 'Cut and fade audio clips without installing anything.',
    longDescription: 'Trim the start or end of an audio clip, add fade-in or fade-out, download the result. Runs fully in your browser.',
    category: 'audio',
    tags: ['audio', 'mp3', 'wav', 'trim', 'cut', 'fade', 'edit', 'music'],
    url: './audio-trimmer/',
    status: 'live',
  },
  {
    id: 'qr-generator',
    title: 'QR Code Generator',
    description: 'Turn a link or text into a QR code you can download.',
    longDescription: 'Paste any link or text, get a high-resolution QR code as PNG or SVG. No signup, no watermark.',
    category: 'dev',
    tags: ['qr', 'qrcode', 'barcode', 'link', 'scan'],
    url: './qr-generator/',
    status: 'live',
  },
  {
    id: 'password-generator',
    title: 'Password Generator',
    description: 'Create strong, random passwords you can actually remember settings for.',
    longDescription: 'Pick length, character types, and whether to avoid similar-looking characters. Generate and copy in one click. Everything happens in your browser — passwords are not logged anywhere.',
    category: 'text',
    tags: ['password', 'security', 'random', 'generator'],
    url: './password-generator/',
    status: 'live',
  },
  {
    id: 'stopwatch',
    title: 'Stopwatch with Splits',
    description: 'A stopwatch that records lap splits with your own notes, and copy-friendly timecodes.',
    longDescription: 'Start, split, add a short description per split, edit descriptions, and copy any timecode or split + note with one click. HH:MM:SS, no milliseconds. Great for video editing, workouts, or logging steps.',
    category: 'text',
    tags: ['stopwatch', 'timer', 'lap', 'split', 'timecode', 'video editing'],
    url: './stopwatch/',
    status: 'live',
  },
  {
    id: 'bulk-image-resizer',
    title: 'Bulk Image Resizer',
    description: 'Drop in many images, get them all cropped/resized to the exact size and format you need.',
    longDescription: 'For writers and content creators who need a fixed ratio and size (e.g. 2:1 at 2000×1000, JPEG). Drop a batch of images, pick a preset or custom size, download the processed set as a .zip. Runs fully in your browser.',
    category: 'image',
    tags: ['bulk', 'batch', 'resize', 'crop', 'ratio', 'thumbnail', 'jpeg', 'article', 'writer'],
    url: './bulk-image-resizer/',
    status: 'live',
  },
  {
    id: 'pseudo-word-generator',
    title: 'Pseudo Word Generator',
    description: 'Generate fake-but-pronounceable words — good for naming projects, characters, or test data.',
    longDescription: 'Pick a length range and a style (Latin-ish, Fantasy, Tech-brand), get a list of invented words you can actually say. Copy the whole list with one click.',
    category: 'text',
    tags: ['name', 'generator', 'brand', 'random', 'word', 'fake', 'lorem'],
    url: './pseudo-word/',
    status: 'live',
  },
  {
    id: 'image-to-text',
    title: 'Image to Text (OCR)',
    description: 'Extract text from a photo or screenshot, right in your browser.',
    longDescription: 'Drop an image, get the text out. Runs fully on your device using Tesseract.js — no upload. Best for printed text and screenshots; handwriting is hit-or-miss.',
    category: 'image',
    tags: ['ocr', 'extract', 'text', 'screenshot', 'scan', 'tesseract'],
    url: '#',
    status: 'coming-soon',
  },
  {
    id: 'exam-generator',
    title: 'Exam / Reviewer Generator',
    description: 'Paste a topic or notes, get 10–50 multiple-choice questions for practice.',
    longDescription: 'Drop in a topic, a block of notes, or a text file, pick how many questions you want, and get a practice quiz with answers. Powered by Google Gemini.',
    category: 'ai',
    tags: ['quiz', 'exam', 'reviewer', 'multiple choice', 'study', 'flashcards', 'test', 'gemini'],
    url: '#',
    status: 'coming-soon',
  },
  {
    id: 'json-formatter',
    title: 'JSON Formatter',
    description: 'Paste messy JSON, get it pretty-printed, minified, or validated.',
    longDescription: 'Format, minify, and validate JSON. Tells you exactly where the syntax error is if it fails. Pure browser — nothing uploaded.',
    category: 'dev',
    tags: ['json', 'format', 'beautify', 'minify', 'validate', 'lint'],
    url: './json-formatter/',
    status: 'live',
  },
  {
    id: 'regex-tester',
    title: 'Regex Tester',
    description: 'Test regular expressions with live match highlighting.',
    longDescription: 'Type a regex, type sample text, see matches highlighted in real time. Shows capture groups. No login, no history stored.',
    category: 'dev',
    tags: ['regex', 'regular expression', 'match', 'pattern', 'tester'],
    url: './regex-tester/',
    status: 'live',
  },
  {
    id: 'diff-checker',
    title: 'Diff Checker',
    description: 'Compare two blocks of text and see exactly what changed.',
    longDescription: 'Paste two texts, get a side-by-side (or inline) diff with additions and removals highlighted. Good for comparing configs, drafts, or code.',
    category: 'dev',
    tags: ['diff', 'compare', 'text', 'changes'],
    url: './diff-checker/',
    status: 'live',
  },
  {
    id: 'unit-converters',
    title: 'Web Dev Unit Converter',
    description: 'Convert px↔rem, hex↔rgba, and Unix timestamps↔ISO dates.',
    longDescription: 'A small pack of the three conversions web developers hit most often. Paste one, get the others instantly.',
    category: 'dev',
    tags: ['unit', 'converter', 'px', 'rem', 'hex', 'rgba', 'color', 'timestamp', 'epoch', 'iso date'],
    url: './unit-converter/',
    status: 'live',
  },
  {
    id: 'token-counter',
    title: 'AI Token Counter',
    description: 'See how many tokens your prompt will cost before you send it to ChatGPT or Claude.',
    longDescription: 'Paste text, pick the model family (GPT, Claude, Gemini), see the token count and approximate characters. Useful for staying under context limits.',
    category: 'ai',
    tags: ['token', 'count', 'llm', 'gpt', 'claude', 'gemini', 'context', 'tiktoken'],
    url: '#',
    status: 'coming-soon',
  },
  {
    id: 'svg-optimizer',
    title: 'SVG Optimizer',
    description: 'Strip hidden bloat out of SVG files to make them smaller and cleaner.',
    longDescription: 'Drop an SVG, get a smaller one back — metadata removed, paths simplified, whitespace cleaned. Runs in your browser.',
    category: 'image',
    tags: ['svg', 'optimize', 'compress', 'minify', 'vector', 'icon'],
    url: './svg-optimizer/',
    status: 'live',
  },
  {
    id: 'pdf-merger',
    title: 'PDF Merger',
    description: 'Combine multiple PDFs into one — without uploading them anywhere.',
    longDescription: 'Drag in several PDFs, reorder them, download the merged file. Uses pdf-lib in your browser so your documents never leave the device.',
    category: 'dev',
    tags: ['pdf', 'merge', 'combine', 'join', 'document'],
    url: './pdf-merger/',
    status: 'live',
  },
];
