// Juankit - central tool registry. Single source of truth for the hub.
// The long metadata powers search. The short display fields power the homepage cards.

const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'image', label: 'Image' },
  { id: 'audio', label: 'Audio' },
  { id: 'video', label: 'Video' },
  { id: 'ai', label: 'AI' },
  { id: 'dev', label: 'Dev Tools' },
  { id: 'text', label: 'Text' },
];

const TOOL_GROUPS = [
  { id: 'all', label: 'All' },
  { id: 'pdf', label: 'PDF' },
  { id: 'image', label: 'Images' },
  { id: 'code', label: 'Code' },
  { id: 'text', label: 'Text' },
  { id: 'ai', label: 'AI' },
  { id: 'media', label: 'Media' },
];

const TOOLS = [
  {
    id: 'image-editor',
    title: 'Image Editor',
    shortTitle: 'Image Editor',
    hint: 'Crop, draw, annotate',
    description: 'Crop, resize, add shapes and text to your photos - all in your browser.',
    longDescription: 'A simple image editor that works like a lightweight paint program. Add rectangles, circles, lines, and text with custom colors and fonts. Resize and compress before downloading. Your photos never leave your device.',
    category: 'image',
    group: 'image',
    icon: 'image',
    featured: true,
    browserOnly: true,
    tags: ['resize', 'crop', 'compress', 'shapes', 'text', 'draw', 'paint', 'jpeg', 'png', 'webp', 'photo', 'annotate'],
    url: './image-editor/',
    status: 'live',
  },
  {
    id: 'folder-tool',
    title: 'Folder Creator',
    shortTitle: 'Folder Creator',
    hint: 'Build folder ZIPs',
    description: 'Type out folder names and download the real folder structure as a .zip.',
    longDescription: 'List your folders and files, click a button, get a .zip file with the whole structure ready to unzip anywhere. Also makes clean folder diagrams you can paste into a README.',
    category: 'dev',
    group: 'code',
    icon: 'folder',
    browserOnly: true,
    tags: ['folder', 'directory', 'tree', 'ascii', 'readme', 'structure', 'scaffold', 'zip', 'project'],
    url: './folder-tool/',
    status: 'live',
  },
  {
    id: 'prompt-enhancer',
    title: 'Prompt Enhancer',
    shortTitle: 'Prompt Enhancer',
    hint: 'Rewrite better prompts',
    description: 'Turn a rough idea into a detailed AI prompt for ChatGPT, Claude, Midjourney, or Stable Diffusion.',
    longDescription: 'Paste a vague prompt, pick the AI tool you use, and get back a polished version that gives better results. Runs through a small secure backend using an OpenAI-compatible API — your key stays on the server, not in the page. Free to use.',
    category: 'ai',
    group: 'ai',
    icon: 'prompt',
    tags: ['prompt', 'chatgpt', 'midjourney', 'claude', 'stable diffusion', 'gemini', 'ai', 'llm', 'generator'],
    url: './prompt-enhancer/',
    status: 'live',
  },
  {
    id: 'youtube-looper',
    title: 'YouTube Replay',
    shortTitle: 'YouTube Replay',
    hint: 'Loop music or video segments',
    description: 'Loop a specific part of any YouTube video for music practice, review, or replay. Also useful for listening to music on repeat.',
    longDescription: 'Pick a start and end time, play that section on repeat. Useful for music practice, music transcription, language practice, dance, or re-watching a specific moment.',
    category: 'video',
    group: 'media',
    icon: 'video',
    featured: true,
    tags: ['youtube', 'loop', 'replay', 'segment', 'repeat', 'practice', 'music', 'song', 'language'],
    url: './youtube-looper/',
    status: 'live',
  },
  {
    id: 'audio-trimmer',
    title: 'Audio Trimmer',
    shortTitle: 'Audio Trimmer',
    hint: 'Cut and fade audio',
    description: 'Cut and fade audio clips without installing anything.',
    longDescription: 'Trim the start and end of a clip, preview it, and download as WAV or MP3. Runs fully in your browser.',
    category: 'audio',
    group: 'media',
    icon: 'audio',
    featured: true,
    browserOnly: true,
    tags: ['audio', 'mp3', 'wav', 'trim', 'cut', 'fade', 'edit', 'music'],
    url: './audio-trimmer/',
    status: 'live',
  },
  {
    id: 'qr-generator',
    title: 'QR Code Generator',
    shortTitle: 'QR Generator',
    hint: 'Create QR images',
    description: 'Turn a link or text into a QR code you can download.',
    longDescription: 'Paste any link or text, get a high-resolution QR code as PNG or SVG. No signup, no watermark.',
    category: 'dev',
    group: 'code',
    icon: 'qr',
    featured: true,
    browserOnly: true,
    tags: ['qr', 'qrcode', 'barcode', 'link', 'scan'],
    url: './qr-generator/',
    status: 'live',
  },
  {
    id: 'fake-user-generator',
    title: 'Fake User Generator',
    shortTitle: 'Fake Users',
    hint: 'Checkout test profiles',
    description: 'Generate country-matched sample user details for checkout and QA testing.',
    longDescription: 'Create fake user profiles with names, reserved-domain emails, country-formatted phones, and curated public test addresses for UAE, US, UK, and Singapore. Runs fully in your browser with copy-ready fields, JSON, and CSV.',
    category: 'dev',
    group: 'code',
    icon: 'user',
    browserOnly: true,
    tags: ['fake user', 'sample user', 'checkout', 'address', 'phone', 'telephone', 'email', 'test data', 'qa', 'uae', 'arabic name', 'json', 'csv'],
    url: './fake-user-generator/',
    status: 'live',
  },
  {
    id: 'password-generator',
    title: 'Password Generator',
    shortTitle: 'Passwords',
    hint: 'Generate strong passwords',
    description: 'Create strong, random passwords you can actually remember settings for.',
    longDescription: 'Pick length, character types, and whether to avoid similar-looking characters. Generate and copy in one click. Everything happens in your browser, and passwords are not logged anywhere.',
    category: 'text',
    group: 'text',
    icon: 'password',
    browserOnly: true,
    tags: ['password', 'security', 'random', 'generator'],
    url: './password-generator/',
    status: 'live',
  },
  {
    id: 'stopwatch',
    title: 'Stopwatch with Splits',
    shortTitle: 'Stopwatch',
    hint: 'Splits and notes',
    description: 'A stopwatch that records lap splits with your own notes, and copy-friendly timecodes.',
    longDescription: 'Start, split, add a short description per split, edit descriptions, and copy any timecode or split plus note with one click. HH:MM:SS, no milliseconds. Great for video editing, workouts, or logging steps.',
    category: 'text',
    group: 'text',
    icon: 'timer',
    browserOnly: true,
    tags: ['stopwatch', 'timer', 'lap', 'split', 'timecode', 'video editing'],
    url: './stopwatch/',
    status: 'live',
  },
  {
    id: 'bulk-image-resizer',
    title: 'Bulk Image Resizer',
    shortTitle: 'Image Resizer',
    hint: 'Batch crop and resize',
    description: 'Drop in many images, get them all cropped or resized to the exact size and format you need.',
    longDescription: 'For writers and content creators who need a fixed ratio and size, such as 2:1 at 2000x1000 JPEG. Drop a batch of images, pick a preset or custom size, download the processed set as a .zip. Runs fully in your browser.',
    category: 'image',
    group: 'image',
    icon: 'resize',
    featured: false,
    browserOnly: true,
    tags: ['bulk', 'batch', 'resize', 'crop', 'ratio', 'thumbnail', 'jpeg', 'article', 'writer'],
    url: './bulk-image-resizer/',
    status: 'live',
  },
  {
    id: 'pseudo-word-generator',
    title: 'Pseudo Word Generator',
    shortTitle: 'Pseudo Words',
    hint: 'Invent names fast',
    description: 'Generate fake but pronounceable words for naming projects, characters, or test data.',
    longDescription: 'Pick a length range and a style, such as Latin-ish, fantasy, or tech-brand, then get a list of invented words you can actually say. Copy the whole list with one click.',
    category: 'text',
    group: 'text',
    icon: 'word',
    browserOnly: true,
    tags: ['name', 'generator', 'brand', 'random', 'word', 'fake', 'lorem'],
    url: './pseudo-word/',
    status: 'live',
  },
  {
    id: 'image-to-text',
    title: 'Image to Text (OCR)',
    shortTitle: 'OCR',
    hint: 'Extract photo text',
    description: 'Extract text from a photo or screenshot, right in your browser.',
    longDescription: 'Drop an image, get the text out. Runs fully on your device using Tesseract.js. Best for printed text and screenshots; handwriting is hit-or-miss.',
    category: 'image',
    group: 'image',
    icon: 'ocr',
    browserOnly: true,
    tags: ['ocr', 'extract', 'text', 'screenshot', 'scan', 'tesseract'],
    url: '#',
    status: 'coming-soon',
  },
  {
    id: 'exam-generator',
    title: 'Exam / Reviewer Generator',
    shortTitle: 'Exam Generator',
    hint: 'Practice questions',
    description: 'Paste a topic or notes, get 10-50 multiple-choice questions for practice.',
    longDescription: 'Drop in a topic, a block of notes, or a text file, pick how many questions you want, and get a practice quiz with answers. Planned: same secure AI-backend pattern as the Prompt Enhancer.',
    category: 'ai',
    group: 'ai',
    icon: 'exam',
    tags: ['quiz', 'exam', 'reviewer', 'multiple choice', 'study', 'flashcards', 'test', 'ai'],
    url: '#',
    status: 'coming-soon',
  },
  {
    id: 'json-formatter',
    title: 'JSON Formatter',
    shortTitle: 'JSON Formatter',
    hint: 'Format and validate',
    description: 'Paste messy JSON, get it pretty-printed, minified, or validated.',
    longDescription: 'Format, minify, and validate JSON. Tells you exactly where the syntax error is if it fails. Pure browser, nothing uploaded.',
    category: 'dev',
    group: 'code',
    icon: 'json',
    featured: false,
    browserOnly: true,
    tags: ['json', 'format', 'beautify', 'minify', 'validate', 'lint'],
    url: './json-formatter/',
    status: 'live',
  },
  {
    id: 'regex-tester',
    title: 'Regex Tester',
    shortTitle: 'Regex Tester',
    hint: 'Live match checks',
    description: 'Test regular expressions with live match highlighting.',
    longDescription: 'Type a regex, type sample text, see matches highlighted in real time. Shows capture groups. No login, no history stored.',
    category: 'dev',
    group: 'code',
    icon: 'regex',
    browserOnly: true,
    tags: ['regex', 'regular expression', 'match', 'pattern', 'tester'],
    url: './regex-tester/',
    status: 'live',
  },
  {
    id: 'diff-checker',
    title: 'Diff Checker',
    shortTitle: 'Diff Checker',
    hint: 'Compare text blocks',
    description: 'Compare two blocks of text and see exactly what changed.',
    longDescription: 'Paste two texts, get a side-by-side or inline diff with additions and removals highlighted. Good for comparing configs, drafts, or code.',
    category: 'dev',
    group: 'code',
    icon: 'diff',
    browserOnly: true,
    tags: ['diff', 'compare', 'text', 'changes'],
    url: './diff-checker/',
    status: 'live',
  },
  {
    id: 'unit-converters',
    title: 'Web Dev Unit Converter',
    shortTitle: 'Unit Converter',
    hint: 'px, rem, color, time',
    description: 'Convert px to rem, hex to rgba, and Unix timestamps to ISO dates.',
    longDescription: 'A small pack of the three conversions web developers hit most often. Paste one, get the others instantly.',
    category: 'dev',
    group: 'code',
    icon: 'unit',
    browserOnly: true,
    tags: ['unit', 'converter', 'px', 'rem', 'hex', 'rgba', 'color', 'timestamp', 'epoch', 'iso date'],
    url: './unit-converter/',
    status: 'live',
  },
  {
    id: 'token-counter',
    title: 'AI Token Counter',
    shortTitle: 'Token Counter',
    hint: 'Estimate prompt size',
    description: 'See how many tokens your prompt will cost before you send it to ChatGPT or Claude.',
    longDescription: 'Paste text, pick the model family, such as GPT, Claude, or Gemini, then see the token count and approximate characters. Useful for staying under context limits.',
    category: 'ai',
    group: 'ai',
    icon: 'token',
    browserOnly: true,
    tags: ['token', 'count', 'llm', 'gpt', 'claude', 'gemini', 'context', 'tiktoken'],
    url: '#',
    status: 'coming-soon',
  },
  {
    id: 'svg-optimizer',
    title: 'SVG Optimizer',
    shortTitle: 'SVG Optimizer',
    hint: 'Clean SVG files',
    description: 'Strip hidden bloat out of SVG files to make them smaller and cleaner.',
    longDescription: 'Drop an SVG, get a smaller one back. Metadata removed, paths simplified, whitespace cleaned. Runs in your browser.',
    category: 'image',
    group: 'image',
    icon: 'svg',
    featured: true,
    browserOnly: true,
    tags: ['svg', 'optimize', 'compress', 'minify', 'vector', 'icon'],
    url: './svg-optimizer/',
    status: 'live',
  },
  {
    id: 'pdf-editor',
    title: 'PDF Editor',
    shortTitle: 'PDF Editor',
    hint: 'Sign and annotate',
    description: 'Add text, shapes, drawings, and signatures to PDFs without uploading them.',
    longDescription: 'Edit a PDF in your browser by adding text, rectangles, ellipses, lines, freehand drawing, and uploaded signatures or images. Includes local white background cleanup for signature images, then downloads a flattened PDF copy.',
    category: 'dev',
    group: 'pdf',
    icon: 'pdf',
    featured: true,
    browserOnly: true,
    tags: ['pdf', 'edit', 'editor', 'sign', 'signature', 'annotate', 'text', 'draw', 'shapes', 'document'],
    url: './pdf-editor/',
    status: 'live',
  },
  {
    id: 'pdf-to-images',
    title: 'PDF to Images',
    shortTitle: 'PDF to Images',
    hint: 'Export PDF pages',
    description: 'Turn PDF pages into PNG, JPG, or WebP images without uploading the file.',
    longDescription: 'Drop in a PDF, choose all pages or a range like 1,3,5-8, pick PNG, JPG, or WebP, then download one image or a ZIP of all converted pages. Runs in your browser so your document stays on your device.',
    category: 'dev',
    group: 'pdf',
    icon: 'image',
    browserOnly: true,
    tags: ['pdf', 'image', 'png', 'jpg', 'jpeg', 'webp', 'convert', 'pages', 'zip'],
    url: './pdf-to-images/',
    status: 'live',
  },
  {
    id: 'pdf-merger',
    title: 'PDF Merger',
    shortTitle: 'PDF Merger',
    hint: 'Combine PDFs',
    description: 'Combine multiple PDFs into one without uploading them anywhere.',
    longDescription: 'Drag in several PDFs, reorder them, download the merged file. Uses pdf-lib in your browser so your documents never leave the device.',
    category: 'dev',
    group: 'pdf',
    icon: 'merge',
    browserOnly: true,
    tags: ['pdf', 'merge', 'combine', 'join', 'document'],
    url: './pdf-merger/',
    status: 'live',
  },
];

function iconMarkup(icon) {
  const icons = {
    pdf: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M7 3h7l4 4v14H7z"/><path d="M14 3v5h5"/><path d="M8.8 15h6.4"/><path d="M8.8 18h4.6"/></svg>',
    merge: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M6 4h8v8H6z"/><path d="M10 12h8v8h-8z"/><path d="M14 8h3v3"/></svg>',
    image: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="5" width="16" height="14" rx="2"/><path d="m7 16 3.5-4 3 3 2-2.2L19 16"/><circle cx="9" cy="9" r="1.2"/></svg>',
    resize: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="5" width="14" height="14" rx="2"/><path d="M9 5H5v4"/><path d="M15 19h4v-4"/><path d="m5 5 5 5"/><path d="m19 19-5-5"/></svg>',
    folder: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7h7l2 2h9v9.5A2.5 2.5 0 0 1 18.5 21h-13A2.5 2.5 0 0 1 3 18.5z"/><path d="M3 7v-1.5A2.5 2.5 0 0 1 5.5 3h4L12 5.5h6.5A2.5 2.5 0 0 1 21 8"/></svg>',
    prompt: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M5 6h10a3 3 0 0 1 3 3v5a3 3 0 0 1-3 3H9l-4 3v-3a3 3 0 0 1-3-3V9a3 3 0 0 1 3-3z"/><path d="M18 3v4"/><path d="M16 5h4"/></svg>',
    video: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="6" width="16" height="12" rx="2"/><path d="m10 9 5 3-5 3z"/></svg>',
    audio: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M4 13v-2"/><path d="M8 16V8"/><path d="M12 19V5"/><path d="M16 16V8"/><path d="M20 13v-2"/></svg>',
    qr: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="4" width="6" height="6"/><rect x="14" y="4" width="6" height="6"/><rect x="4" y="14" width="6" height="6"/><path d="M14 14h2v2h-2z"/><path d="M18 14h2v6h-6v-2"/></svg>',
    user: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="4"/><path d="M5 20a7 7 0 0 1 14 0"/><path d="M17.5 7.5h3"/><path d="M19 6v3"/></svg>',
    password: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><circle cx="8" cy="12" r="3"/><path d="M11 12h9"/><path d="M17 12v3"/><path d="M14 12v2"/></svg>',
    timer: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="13" r="7"/><path d="M9 2h6"/><path d="M12 6V2"/><path d="m12 13 3-2"/></svg>',
    word: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M5 6h14"/><path d="M7 10h10"/><path d="M8 14h8"/><path d="M10 18h4"/></svg>',
    ocr: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M4 8V5h3"/><path d="M17 5h3v3"/><path d="M20 16v3h-3"/><path d="M7 19H4v-3"/><path d="M7 12h10"/><path d="M9 9h6"/><path d="M9 15h6"/></svg>',
    exam: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M7 4h10v16H7z"/><path d="m9 9 1 1 2-2"/><path d="M14 9h2"/><path d="m9 15 1 1 2-2"/><path d="M14 15h2"/></svg>',
    json: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M9 5H7a2 2 0 0 0-2 2v2a2 2 0 0 1-2 2 2 2 0 0 1 2 2v2a2 2 0 0 0 2 2h2"/><path d="M15 5h2a2 2 0 0 1 2 2v2a2 2 0 0 0 2 2 2 2 0 0 0-2 2v2a2 2 0 0 1-2 2h-2"/></svg>',
    regex: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/><path d="m7 7 10 10"/><path d="m17 7-10 10"/></svg>',
    diff: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M5 8h9"/><path d="M5 16h9"/><path d="M18 5v6"/><path d="M15 8h6"/><path d="M15 16h6"/></svg>',
    unit: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M5 7h14"/><path d="M5 17h14"/><path d="M7 5v4"/><path d="M17 15v4"/><path d="m9 12-3-3 3-3"/><path d="m15 12 3 3-3 3"/></svg>',
    token: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3 4 7v10l8 4 8-4V7z"/><path d="M4 7l8 4 8-4"/><path d="M12 11v10"/></svg>',
    svg: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="M8 9h8"/><path d="M8 15h8"/></svg>',
    tool: '<svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="4" width="7" height="7" rx="1.5"/><rect x="13" y="4" width="7" height="7" rx="1.5"/><rect x="4" y="13" width="7" height="7" rx="1.5"/><rect x="13" y="13" width="7" height="7" rx="1.5"/></svg>',
  };

  return icons[icon] || icons.tool;
}
